/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class marshal_cv_FeatureDetector */

#ifndef _Included_marshal_cv_FeatureDetector
#define _Included_marshal_cv_FeatureDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     marshal_cv_FeatureDetector
 * Method:    getOpenCvVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_marshal_cv_FeatureDetector_getOpenCvVersion
  (JNIEnv *, jobject);

/*
 * Class:     marshal_cv_FeatureDetector
 * Method:    isOpticalFlowMoved
 * Signature: ([BII)Z
 */
JNIEXPORT jboolean JNICALL Java_marshal_cv_FeatureDetector_isOpticalFlowMoved
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
